export interface TermRecord {
  zh: string;
  pinyin: string;
  en: string;
  side: 'direct' | 'paternal' | 'maternal' | 'affinal';
  alt?: string;
}

export const TERMS: Record<string, TermRecord> = {
  self:                       { zh: '我',      pinyin: 'wǒ',            en: 'me',                              side: 'direct' },
  father:                     { zh: '爸爸',    pinyin: 'bàba',          en: 'father',                          side: 'direct',   alt: '父亲 fùqīn' },
  mother:                     { zh: '妈妈',    pinyin: 'māma',          en: 'mother',                          side: 'direct',   alt: '母亲 mǔqīn' },
  paternal_grandfather:       { zh: '爷爷',    pinyin: 'yéye',          en: "father's father",                 side: 'paternal', alt: '祖父 zǔfù' },
  paternal_grandmother:       { zh: '奶奶',    pinyin: 'nǎinai',        en: "father's mother",                 side: 'paternal', alt: '祖母 zǔmǔ' },
  maternal_grandfather:       { zh: '外公',    pinyin: 'wàigōng',       en: "mother's father",                 side: 'maternal', alt: '姥爷 lǎoye' },
  maternal_grandmother:       { zh: '外婆',    pinyin: 'wàipó',         en: "mother's mother",                 side: 'maternal', alt: '姥姥 lǎolao' },
  paternal_great_grandfather:      { zh: '曾祖父',   pinyin: 'zēngzǔfù',       en: "father's father's father",             side: 'paternal', alt: '太爷爷 tàiyéye' },
  paternal_great_grandmother:      { zh: '曾祖母',   pinyin: 'zēngzǔmǔ',       en: "father's father's mother",             side: 'paternal', alt: '太奶奶 tàinǎinai' },
  maternal_great_grandfather:      { zh: '外曾祖父', pinyin: 'wàizēngzǔfù',    en: "mother's grandfather",                 side: 'maternal', alt: '太姥爷' },
  maternal_great_grandmother:      { zh: '外曾祖母', pinyin: 'wàizēngzǔmǔ',    en: "mother's grandmother",                 side: 'maternal', alt: '太姥姥' },
  paternal_great_great_grandfather:{ zh: '高祖父',   pinyin: 'gāozǔfù',        en: "great-great-grandfather (paternal)",   side: 'paternal', alt: '太太爷爷' },
  paternal_great_great_grandmother:{ zh: '高祖母',   pinyin: 'gāozǔmǔ',        en: "great-great-grandmother (paternal)",   side: 'paternal', alt: '太太奶奶' },
  maternal_great_great_grandfather:{ zh: '外高祖父', pinyin: 'wàigāozǔfù',     en: "great-great-grandfather (maternal)",   side: 'maternal' },
  maternal_great_great_grandmother:{ zh: '外高祖母', pinyin: 'wàigāozǔmǔ',     en: "great-great-grandmother (maternal)",   side: 'maternal' },
  // ── grandparents' siblings' spouses ─────────────────
  paternal_grandfather_older_brother_wife:  { zh: '伯祖母', pinyin: 'bózǔmǔ',   en: "father's father's elder brother's wife",    side: 'paternal' },
  paternal_grandfather_younger_brother_wife:{ zh: '叔祖母', pinyin: 'shūzǔmǔ',  en: "father's father's younger brother's wife",  side: 'paternal' },
  paternal_grandfather_sister_husband:      { zh: '姑祖父', pinyin: 'gūzǔfù',   en: "father's father's sister's husband",        side: 'paternal' },
  paternal_grandmother_brother_wife:        { zh: '舅祖母', pinyin: 'jiùzǔmǔ',  en: "father's mother's brother's wife",          side: 'paternal' },
  paternal_grandmother_sister_husband:      { zh: '姨祖父', pinyin: 'yízǔfù',   en: "father's mother's sister's husband",        side: 'paternal' },
  maternal_grandfather_brother_wife:        { zh: '舅婆',   pinyin: 'jiùpó',    en: "mother's father's brother's wife",          side: 'maternal' },
  maternal_grandfather_sister_husband:      { zh: '姑公',   pinyin: 'gūgōng',   en: "mother's father's sister's husband",        side: 'maternal' },
  maternal_grandmother_brother_wife:        { zh: '舅婆',   pinyin: 'jiùpó',    en: "mother's mother's brother's wife",          side: 'maternal' },
  maternal_grandmother_sister_husband:      { zh: '姨公',   pinyin: 'yígōng',   en: "mother's mother's sister's husband",        side: 'maternal' },

  // ── grandparents' siblings' children's spouses (a=3, b=2 spouses) ──
  pat_gf_older_bro_child_m_wife:   { zh: '表伯母', pinyin: 'biǎobómǔ',    en: "wife of father's father's elder brother's son",    side: 'paternal' },
  pat_gf_older_bro_child_f_husb:   { zh: '表姑丈', pinyin: 'biǎogūzhàng', en: "husband of father's father's elder brother's daughter", side: 'paternal' },
  pat_gf_younger_bro_child_m_wife: { zh: '表叔母', pinyin: 'biǎoshūmǔ',   en: "wife of father's father's younger brother's son",  side: 'paternal' },
  pat_gf_younger_bro_child_f_husb: { zh: '表姑丈', pinyin: 'biǎogūzhàng', en: "husband of father's father's younger brother's daughter", side: 'paternal' },
  pat_gf_sis_child_m_wife:         { zh: '表舅妈', pinyin: 'biǎojiùmā',   en: "wife of father's father's sister's son",           side: 'paternal' },
  pat_gf_sis_child_f_husb:         { zh: '表姑丈', pinyin: 'biǎogūzhàng', en: "husband of father's father's sister's daughter",   side: 'paternal' },
  pat_gm_bro_child_m_wife:         { zh: '表舅妈', pinyin: 'biǎojiùmā',   en: "wife of father's mother's brother's son",          side: 'paternal' },
  pat_gm_bro_child_f_husb:         { zh: '表姨丈', pinyin: 'biǎoyízhàng', en: "husband of father's mother's brother's daughter",  side: 'paternal' },
  pat_gm_sis_child_m_wife:         { zh: '表舅妈', pinyin: 'biǎojiùmā',   en: "wife of father's mother's sister's son",           side: 'paternal' },
  pat_gm_sis_child_f_husb:         { zh: '表姨丈', pinyin: 'biǎoyízhàng', en: "husband of father's mother's sister's daughter",   side: 'paternal' },
  mat_gf_bro_child_m_wife:         { zh: '表舅妈', pinyin: 'biǎojiùmā',   en: "wife of mother's father's brother's son",          side: 'maternal' },
  mat_gf_bro_child_f_husb:         { zh: '表姨丈', pinyin: 'biǎoyízhàng', en: "husband of mother's father's brother's daughter",  side: 'maternal' },
  mat_gf_sis_child_m_wife:         { zh: '表舅妈', pinyin: 'biǎojiùmā',   en: "wife of mother's father's sister's son",           side: 'maternal' },
  mat_gf_sis_child_f_husb:         { zh: '表姨丈', pinyin: 'biǎoyízhàng', en: "husband of mother's father's sister's daughter",   side: 'maternal' },
  mat_gm_bro_child_m_wife:         { zh: '表舅妈', pinyin: 'biǎojiùmā',   en: "wife of mother's mother's brother's son",          side: 'maternal' },
  mat_gm_bro_child_f_husb:         { zh: '表姨丈', pinyin: 'biǎoyízhàng', en: "husband of mother's mother's brother's daughter",  side: 'maternal' },
  mat_gm_sis_child_m_wife:         { zh: '表舅妈', pinyin: 'biǎojiùmā',   en: "wife of mother's mother's sister's son",           side: 'maternal' },
  mat_gm_sis_child_f_husb:         { zh: '表姨丈', pinyin: 'biǎoyízhàng', en: "husband of mother's mother's sister's daughter",   side: 'maternal' },

  // ── grandparents' siblings' children (a=3, b=2) ─────
  pat_gf_older_bro_child_m:   { zh: '表伯父', pinyin: 'biǎobófù',  en: "father's father's elder brother's son",   side: 'paternal' },
  pat_gf_older_bro_child_f:   { zh: '表伯母', pinyin: 'biǎobómǔ',  en: "father's father's elder brother's daughter", side: 'paternal' },
  pat_gf_younger_bro_child_m: { zh: '表叔父', pinyin: 'biǎoshūfù', en: "father's father's younger brother's son",  side: 'paternal' },
  pat_gf_younger_bro_child_f: { zh: '表叔母', pinyin: 'biǎoshūmǔ', en: "father's father's younger brother's daughter", side: 'paternal' },
  pat_gf_sis_child_m:         { zh: '表姑父', pinyin: 'biǎogūfù',  en: "father's father's sister's son",           side: 'paternal' },
  pat_gf_sis_child_f:         { zh: '表姑母', pinyin: 'biǎogūmǔ',  en: "father's father's sister's daughter",      side: 'paternal' },
  pat_gm_bro_child_m:         { zh: '表舅父', pinyin: 'biǎojiùfù', en: "father's mother's brother's son",          side: 'paternal' },
  pat_gm_bro_child_f:         { zh: '表舅母', pinyin: 'biǎojiùmǔ', en: "father's mother's brother's daughter",     side: 'paternal' },
  pat_gm_sis_child_m:         { zh: '表姨父', pinyin: 'biǎoyífù',  en: "father's mother's sister's son",           side: 'paternal' },
  pat_gm_sis_child_f:         { zh: '表姨母', pinyin: 'biǎoyímǔ',  en: "father's mother's sister's daughter",      side: 'paternal' },
  mat_gf_bro_child_m:         { zh: '表舅',   pinyin: 'biǎojiù',   en: "mother's father's brother's son",          side: 'maternal' },
  mat_gf_bro_child_f:         { zh: '表姑',   pinyin: 'biǎogū',    en: "mother's father's brother's daughter",     side: 'maternal' },
  mat_gf_sis_child_m:         { zh: '表舅',   pinyin: 'biǎojiù',   en: "mother's father's sister's son",           side: 'maternal' },
  mat_gf_sis_child_f:         { zh: '表姑',   pinyin: 'biǎogū',    en: "mother's father's sister's daughter",      side: 'maternal' },
  mat_gm_bro_child_m:         { zh: '表舅',   pinyin: 'biǎojiù',   en: "mother's mother's brother's son",          side: 'maternal' },
  mat_gm_bro_child_f:         { zh: '表姨',   pinyin: 'biǎoyí',    en: "mother's mother's brother's daughter",     side: 'maternal' },
  mat_gm_sis_child_m:         { zh: '表舅',   pinyin: 'biǎojiù',   en: "mother's mother's sister's son",           side: 'maternal' },
  mat_gm_sis_child_f:         { zh: '表姨',   pinyin: 'biǎoyí',    en: "mother's mother's sister's daughter",      side: 'maternal' },

  // ── grandparents' siblings ────────────────────────────
  paternal_grandfather_older_brother:  { zh: '伯祖父', pinyin: 'bózǔfù',  en: "father's father's elder brother",  side: 'paternal', alt: '伯公 bógōng' },
  paternal_grandfather_younger_brother:{ zh: '叔祖父', pinyin: 'shūzǔfù', en: "father's father's younger brother", side: 'paternal', alt: '叔公 shūgōng' },
  paternal_grandfather_sister:         { zh: '姑祖母', pinyin: 'gūzǔmǔ',  en: "father's father's sister",         side: 'paternal', alt: '姑婆 gūpó' },
  paternal_grandmother_brother:        { zh: '舅祖父', pinyin: 'jiùzǔfù', en: "father's mother's brother",        side: 'paternal', alt: '舅公 jiùgōng' },
  paternal_grandmother_sister:         { zh: '姨祖母', pinyin: 'yízǔmǔ',  en: "father's mother's sister",         side: 'paternal', alt: '姨婆 yípó' },
  maternal_grandfather_brother:        { zh: '舅公',   pinyin: 'jiùgōng', en: "mother's father's brother",        side: 'maternal', alt: '外叔祖父' },
  maternal_grandfather_sister:         { zh: '姑婆',   pinyin: 'gūpó',    en: "mother's father's sister",         side: 'maternal', alt: '外姑祖母' },
  maternal_grandmother_brother:        { zh: '舅公',   pinyin: 'jiùgōng', en: "mother's mother's brother",        side: 'maternal', alt: '外舅祖父' },
  maternal_grandmother_sister:         { zh: '姨婆',   pinyin: 'yípó',    en: "mother's mother's sister",         side: 'maternal', alt: '外姨婆' },

  father_older_brother:       { zh: '伯父',    pinyin: 'bófù',          en: "father's elder brother",          side: 'paternal', alt: '伯伯 bóbo' },
  father_younger_brother:     { zh: '叔叔',    pinyin: 'shūshu',        en: "father's younger brother",        side: 'paternal', alt: '叔父 shūfù' },
  father_sister:              { zh: '姑姑',    pinyin: 'gūgu',          en: "father's sister",                 side: 'paternal', alt: '姑母 gūmǔ' },
  mother_brother:             { zh: '舅舅',    pinyin: 'jiùjiu',        en: "mother's brother",                side: 'maternal', alt: '舅父 jiùfù' },
  mother_sister:              { zh: '姨',      pinyin: 'yí',            en: "mother's sister",                 side: 'maternal', alt: '阿姨 āyí' },
  father_older_brother_wife:  { zh: '伯母',    pinyin: 'bómǔ',          en: "father's elder brother's wife",   side: 'affinal',  alt: '大妈 dàmā' },
  father_younger_brother_wife:{ zh: '婶婶',    pinyin: 'shěnshen',      en: "father's younger brother's wife", side: 'affinal',  alt: '婶母 shěnmǔ' },
  father_sister_husband:      { zh: '姑父',    pinyin: 'gūfù',          en: "father's sister's husband",       side: 'affinal',  alt: '姑丈 gūzhàng' },
  mother_brother_wife:        { zh: '舅妈',    pinyin: 'jiùmā',         en: "mother's brother's wife",         side: 'affinal',  alt: '舅母 jiùmǔ' },
  mother_sister_husband:      { zh: '姨丈',    pinyin: 'yízhàng',       en: "mother's sister's husband",       side: 'affinal',  alt: '姨父 yífù' },
  older_brother:              { zh: '哥哥',    pinyin: 'gēge',          en: 'elder brother',                   side: 'direct' },
  younger_brother:            { zh: '弟弟',    pinyin: 'dìdi',          en: 'younger brother',                 side: 'direct' },
  older_sister:               { zh: '姐姐',    pinyin: 'jiějie',        en: 'elder sister',                    side: 'direct' },
  younger_sister:             { zh: '妹妹',    pinyin: 'mèimei',        en: 'younger sister',                  side: 'direct' },
  older_brother_wife:         { zh: '嫂子',    pinyin: 'sǎozi',         en: "elder brother's wife",            side: 'affinal', alt: '嫂嫂' },
  younger_brother_wife:       { zh: '弟妹',    pinyin: 'dìmèi',         en: "younger brother's wife",          side: 'affinal', alt: '弟媳 dìxí' },
  older_sister_husband:       { zh: '姐夫',    pinyin: 'jiěfu',         en: "elder sister's husband",          side: 'affinal' },
  younger_sister_husband:     { zh: '妹夫',    pinyin: 'mèifu',         en: "younger sister's husband",        side: 'affinal', alt: '妹婿 mèixù' },
  tang_older_male:            { zh: '堂哥',    pinyin: 'tánggē',        en: "father's brother's son (elder)",  side: 'paternal' },
  tang_younger_male:          { zh: '堂弟',    pinyin: 'tángdì',        en: "father's brother's son (younger)",side: 'paternal' },
  tang_older_female:          { zh: '堂姐',    pinyin: 'tángjiě',       en: "father's brother's daughter (elder)",   side: 'paternal' },
  tang_younger_female:        { zh: '堂妹',    pinyin: 'tángmèi',       en: "father's brother's daughter (younger)", side: 'paternal' },
  biao_older_male:            { zh: '表哥',    pinyin: 'biǎogē',        en: 'cousin (elder male)',             side: 'maternal' },
  biao_younger_male:          { zh: '表弟',    pinyin: 'biǎodì',        en: 'cousin (younger male)',           side: 'maternal' },
  biao_older_female:          { zh: '表姐',    pinyin: 'biǎojiě',       en: 'cousin (elder female)',           side: 'maternal' },
  biao_younger_female:        { zh: '表妹',    pinyin: 'biǎomèi',       en: 'cousin (younger female)',         side: 'maternal' },
  son:                        { zh: '儿子',    pinyin: 'érzi',          en: 'son',                             side: 'direct' },
  daughter:                   { zh: '女儿',    pinyin: "nǚ'ér",         en: 'daughter',                        side: 'direct' },
  grandson_via_son:           { zh: '孙子',    pinyin: 'sūnzi',         en: "son's son",                       side: 'paternal' },
  granddaughter_via_son:      { zh: '孙女',    pinyin: 'sūnnǚ',         en: "son's daughter",                  side: 'paternal' },
  grandson_via_daughter:      { zh: '外孙',    pinyin: 'wàisūn',        en: "daughter's son",                  side: 'maternal' },
  granddaughter_via_daughter: { zh: '外孙女',  pinyin: 'wàisūnnǚ',      en: "daughter's daughter",             side: 'maternal' },
  brother_son:                { zh: '侄子',    pinyin: 'zhízi',         en: "brother's son",                   side: 'paternal' },
  brother_daughter:           { zh: '侄女',    pinyin: 'zhínǚ',         en: "brother's daughter",              side: 'paternal' },
  sister_son:                 { zh: '外甥',    pinyin: 'wàishēng',      en: "sister's son",                    side: 'maternal' },
  sister_daughter:            { zh: '外甥女',  pinyin: 'wàishēngnǚ',    en: "sister's daughter",               side: 'maternal' },
  // ── spouse's siblings ────────────────────────────────
  wife_older_brother:        { zh: '大舅子',  pinyin: 'dàjiùzi',     en: "wife's elder brother",           side: 'affinal', alt: '妻兄 qīxiōng' },
  wife_younger_brother:      { zh: '小舅子',  pinyin: 'xiǎojiùzi',   en: "wife's younger brother",         side: 'affinal', alt: '妻弟 qīdì' },
  wife_older_sister:         { zh: '大姨子',  pinyin: 'dàyízi',      en: "wife's elder sister",            side: 'affinal', alt: '妻姐 qījiě' },
  wife_younger_sister:       { zh: '小姨子',  pinyin: 'xiǎoyízi',    en: "wife's younger sister",          side: 'affinal', alt: '妻妹 qīmèi' },
  husband_older_brother:     { zh: '大伯子',  pinyin: 'dàbózi',      en: "husband's elder brother",        side: 'affinal', alt: '大伯 dàbó' },
  husband_younger_brother:   { zh: '小叔子',  pinyin: 'xiǎoshūzi',   en: "husband's younger brother",      side: 'affinal', alt: '小叔 xiǎoshū' },
  husband_older_sister:      { zh: '大姑子',  pinyin: 'dàgūzi',      en: "husband's elder sister",         side: 'affinal', alt: '大姑 dàgū' },
  husband_younger_sister:    { zh: '小姑子',  pinyin: 'xiǎogūzi',    en: "husband's younger sister",       side: 'affinal', alt: '小姑 xiǎogū' },

  // ── spouse's siblings' children ──────────────────────
  wife_brother_son:          { zh: '内侄',    pinyin: 'nèizhí',      en: "wife's brother's son",           side: 'affinal' },
  wife_brother_daughter:     { zh: '内侄女',  pinyin: 'nèizhínǚ',    en: "wife's brother's daughter",      side: 'affinal' },
  wife_sister_son:           { zh: '内甥',    pinyin: 'nèishēng',    en: "wife's sister's son",            side: 'affinal' },
  wife_sister_daughter:      { zh: '内甥女',  pinyin: 'nèishēngnǚ',  en: "wife's sister's daughter",       side: 'affinal' },
  husband_brother_son:       { zh: '侄子',    pinyin: 'zhízi',       en: "husband's brother's son",        side: 'affinal' },
  husband_brother_daughter:  { zh: '侄女',    pinyin: 'zhínǚ',       en: "husband's brother's daughter",   side: 'affinal' },
  husband_sister_son:        { zh: '外甥',    pinyin: 'wàishēng',    en: "husband's sister's son",         side: 'affinal' },
  husband_sister_daughter:   { zh: '外甥女',  pinyin: 'wàishēngnǚ',  en: "husband's sister's daughter",    side: 'affinal' },

  son_wife:                   { zh: '儿媳',    pinyin: 'érxí',          en: "son's wife",                      side: 'affinal', alt: '媳妇 xífù' },
  daughter_husband:           { zh: '女婿',    pinyin: 'nǚxù',          en: "daughter's husband",              side: 'affinal' },
  husband:                    { zh: '丈夫',    pinyin: 'zhàngfu',       en: 'husband',                         side: 'affinal', alt: '老公 lǎogōng' },
  wife:                       { zh: '妻子',    pinyin: 'qīzi',          en: 'wife',                            side: 'affinal', alt: '老婆 lǎopó' },
  wife_father:                { zh: '岳父',    pinyin: 'yuèfù',         en: "wife's father",                   side: 'affinal', alt: '丈人 zhàngren' },
  wife_mother:                { zh: '岳母',    pinyin: 'yuèmǔ',         en: "wife's mother",                   side: 'affinal', alt: '丈母娘 zhàngmuniáng' },
  husband_father:             { zh: '公公',    pinyin: 'gōnggong',      en: "husband's father",                side: 'affinal' },
  husband_mother:             { zh: '婆婆',    pinyin: 'pópo',          en: "husband's mother",                side: 'affinal' },
};

export const SPOUSE_OF: Record<string, string> = {
  father:                  'mother',
  mother:                  'father',
  paternal_grandfather_older_brother:   'paternal_grandfather_older_brother_wife',
  paternal_grandfather_younger_brother: 'paternal_grandfather_younger_brother_wife',
  paternal_grandfather_sister:          'paternal_grandfather_sister_husband',
  paternal_grandmother_brother:         'paternal_grandmother_brother_wife',
  paternal_grandmother_sister:          'paternal_grandmother_sister_husband',
  pat_gf_older_bro_child_m:   'pat_gf_older_bro_child_m_wife',
  pat_gf_older_bro_child_f:   'pat_gf_older_bro_child_f_husb',
  pat_gf_younger_bro_child_m: 'pat_gf_younger_bro_child_m_wife',
  pat_gf_younger_bro_child_f: 'pat_gf_younger_bro_child_f_husb',
  pat_gf_sis_child_m:         'pat_gf_sis_child_m_wife',
  pat_gf_sis_child_f:         'pat_gf_sis_child_f_husb',
  pat_gm_bro_child_m:         'pat_gm_bro_child_m_wife',
  pat_gm_bro_child_f:         'pat_gm_bro_child_f_husb',
  pat_gm_sis_child_m:         'pat_gm_sis_child_m_wife',
  pat_gm_sis_child_f:         'pat_gm_sis_child_f_husb',
  mat_gf_bro_child_m:         'mat_gf_bro_child_m_wife',
  mat_gf_bro_child_f:         'mat_gf_bro_child_f_husb',
  mat_gf_sis_child_m:         'mat_gf_sis_child_m_wife',
  mat_gf_sis_child_f:         'mat_gf_sis_child_f_husb',
  mat_gm_bro_child_m:         'mat_gm_bro_child_m_wife',
  mat_gm_bro_child_f:         'mat_gm_bro_child_f_husb',
  mat_gm_sis_child_m:         'mat_gm_sis_child_m_wife',
  mat_gm_sis_child_f:         'mat_gm_sis_child_f_husb',
  maternal_grandfather_brother:         'maternal_grandfather_brother_wife',
  maternal_grandfather_sister:          'maternal_grandfather_sister_husband',
  maternal_grandmother_brother:         'maternal_grandmother_brother_wife',
  maternal_grandmother_sister:          'maternal_grandmother_sister_husband',
  father_older_brother:    'father_older_brother_wife',
  father_younger_brother:  'father_younger_brother_wife',
  father_sister:           'father_sister_husband',
  mother_brother:          'mother_brother_wife',
  mother_sister:           'mother_sister_husband',
  older_brother:           'older_brother_wife',
  younger_brother:         'younger_brother_wife',
  older_sister:            'older_sister_husband',
  younger_sister:          'younger_sister_husband',
  son:                     'son_wife',
  daughter:                'daughter_husband',
};

export function lookup(key: string): TermRecord & { key: string } {
  const rec = TERMS[key];
  if (!rec) throw new Error(`No term for key "${key}"`);
  return { key, ...rec };
}
